In [2]:
import requests

In [5]:
URL ="https://stephen-king-api.onrender.com/api/books"
res = requests.get(URL)

In [7]:
data = res.json()

In [14]:
import pandas as pd

df = pd.json_normalize(data["data"])
df = df[['id','Title','Year','ISBN']]

In [15]:
df

    id          Title  Year               ISBN
0    1         Carrie  1974  978-0-385-08695-0
1    2    Salem's Lot  1975  978-0-385-00751-1
2    3    The Shining  1977  978-0-385-12167-5
3    4           Rage  1977  978-0-451-07645-8
4    5      The Stand  1978  978-0-385-12168-2
..  ..            ...   ...                ...
58  59   The Outsider  2018  978-1-50118-098-9
59  60      Elevation  2018  978-1-98210-231-9
60  61  The Institute  2019  978-1-98211-056-7
61  62          Later  2021  978-1-78909-649-1
62  63  Billy Summers  2021  978-1-982-17361-6

[63 rows x 4 columns]

In [91]:
import requests
URL = "https://www.scrapethissite.com/pages/simple/"

res= requests.get(URL)

In [92]:
with open("scraped_data/data1.html", "wb") as f:
    f.write(res.content)

In [28]:
pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\mayan\anaconda3\lib\site-packages (4.12.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\mayan\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Note: you may need to restart the kernel to use updated packages.

In [121]:
from bs4 import BeautifulSoup

with open("scraped_data/data1.html", "r") as f:
    html_content = f.read()

soup = BeautifulSoup(html_content, "lxml")

In [61]:
all_h3 = soup.find_all("h3")
all_countries = []
for h3 in all_h3:
    name = h3.get_text(strip=True)
    population = (h3.find_next("div").select_one("span.country-population").get_text(strip=True))
    all_countries.append([name,population])

In [66]:
import pandas as pd 
df = pd.DataFrame(all_countries,columns= ["Name","Population"])

In [67]:
df.to_csv("Cleaned_data/data.csv",index= False )

In [68]:
#ACTIVITY OF WEBSCRAPPING

In [105]:
import requests
from bs4 import BeautifulSoup

SyntaxError: invalid syntax (3769678672.py, line 3)

In [95]:
page_count = 1
while True :
    URL = f"https://quotes.toscrape.com/page/{page_count}/"
    res = requests.get(URL)
    
    soup = BeautifulSoup(res.text,"lxml")
    quotes = soup.select("div.quote")
    if not quotes:
        print(f"total pages = {page_count - 1} ")
        break 
    with open(f"scraped_data/quotes on page{page_count}.html", "wb") as f:
        f.write(res.content)
    print(f"Data dounloaded from page {page_count}")
    page_count += 1

Data dounloaded from page 1
Data dounloaded from page 2
Data dounloaded from page 3
Data dounloaded from page 4
Data dounloaded from page 5
Data dounloaded from page 6
Data dounloaded from page 7
Data dounloaded from page 8
Data dounloaded from page 9
Data dounloaded from page 10
total pages = 11

In [96]:
#Extract Information

In [188]:
page_count = 1
quotes = []
while page_count<11:
    with open(f"scraped_data/quotes_on_page{page_count}.html", "rb") as f:
        html_content = f.read()

    soup = BeautifulSoup(html_content, "lxml")
    all_quotes = soup.select("div.quote")
    for aq in all_quotes:
        #auther = (aq.find("small", class_="author").text)
        author = (aq.select_one("small.author").get_text())
        quote = (aq.select_one("span.text").get_text())
        tags = [tag.get_text(strip=True) for tag in aq.select("a.tag")]
        quotes.append([author,quote,tags])
    page_count +=1

In [189]:
import pandas as pd 
df = pd.DataFrame(quotes,columns= ["auther","Quotes","tags"])

In [190]:
df

,auther,Quotes,tags
0,Albert Einstein,“The world as we have created it is a process ...,"[change, deep-thoughts, thinking, world]"
1,J.K. Rowling,"“It is our choices, Harry, that show what we t...","[abilities, choices]"
2,Albert Einstein,“There are only two ways to live your life. On...,"[inspirational, life, live, miracle, miracles]"
3,Jane Austen,"“The person, be it gentleman or lady, who has ...","[aliteracy, books, classic, humor]"
4,Marilyn Monroe,"“Imperfection is beauty, madness is genius and...","[be-yourself, inspirational]"
...,...,...,...
95,Harper Lee,“You never really understand a person until yo...,[better-life-empathy]
96,Madeleine L'Engle,“You have to write the book that wants to be w...,"[books, children, difficult, grown-ups, write,..."
97,Mark Twain,“Never tell the truth to people who are not wo...,[truth]
98,Dr. Seuss,"“A person's a person, no matter how small.”",[inspirational]
99,George R.R. Martin,“... a mind needs books as a sword needs a whe...,"[books, mind]"

In [192]:
df.to_json("Cleaned_data/Quotes.csv",index= False )